// LINKS ROUTER
const HOME_PAGE = '/';
const LOGIN_PAGE = '/login';
const REGISTER_PAGE = '/register';
const CONTACT_PAGE = '/contact';
const NEWS_PAGE = '/news';

// REDUCERS
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

// LOCALSTORAGE KEY CONSTANTS
const LOCAL_STORAGE_TOKEN_KEY = '@token';
const LOCAL_STORAGE_CREDENTIALS_KEY = '@credentials';
const CLEAR_STORE = 'CLEAR_STORE';

export {HOME_PAGE, LOGIN_PAGE, REGISTER_PAGE, CONTACT_PAGE, NEWS_PAGE};
export {LOGIN_SUCCESS, LOGIN_FAILURE};
export {LOCAL_STORAGE_TOKEN_KEY, LOCAL_STORAGE_CREDENTIALS_KEY, CLEAR_STORE};



